In [2]:
import torch

In [3]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
print(x.shape)
x.numel()
print(x.reshape(3,4))


torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
torch.zeros((3,4))
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
x = torch.tensor([[1.,2,3],[4,5,6],[7,8,9]])#只要有一个是浮点数，整个张量的元素都视为浮点数
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x + y

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

In [7]:
x = torch.arange(12,dtype=torch.float).reshape(3,4)
y = torch.arange(12,dtype=torch.float).reshape(3,4)
print(torch.cat((x,y),dim=0))
print(torch.cat((x,y),dim=1))
print(torch.cat((x,y),dim=-1))
x == y
print(torch.sum(x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])
tensor(66.)


In [8]:
x = torch.arange(3).reshape([3,1])
y = torch.arange(2).reshape([1,2])
print(x,y)
print(x+y)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [9]:
x = torch.arange(12).reshape([3,4])
print(x[1])
print(x[1:3])
print(x[1,3])
x[1] = 12
print(x)

tensor([4, 5, 6, 7])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(7)
tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])


In [10]:
x = torch.tensor(1.0)
print(x)
print(x.item())
x = x.item()
int(x)

tensor(1.)
1.0


1

In [11]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('numrooms,alley,price\n')
    f.write('NA,pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [12]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   numrooms alley   price
0       NaN  pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [13]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   numrooms alley
0       3.0  pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [14]:
inputs = pd.get_dummies(inputs,dummy_na=True)
#这是一个 Pandas 提供的强大函数，用于将分类变量（Categorical Variables）转换为独热编码。
#原理：它会扫描数据中的每一列。如果发现某列是文本（类别），它就会根据这一列里有多少种不同的取值，生成多少个新的“0/1”列。
#举例：如果 Alley 列有 "Pave" 和 "Grvl" 两种值，它就会生成两列：Alley_Pave 和 Alley_Grvl。如果是 "Pave"，则前者为 1，后者为 0。
print(inputs)

   numrooms  alley_pave  alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [15]:
inputs.iloc[:, 1:3] *= 1
print(inputs)

   numrooms  alley_pave  alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [16]:
X,Y = torch.tensor(inputs.values),torch.tensor(outputs.values)
#将 Pandas 表格数据转换为 PyTorch 深度学习框架能够识别和计算的张量（Tensor）格式。
X,Y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [18]:
X,Y = torch.tensor([[1,1,2,3],[3,2,5,6],[4,5,6,7]]),torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(X,Y)

tensor([[1, 1, 2, 3],
        [3, 2, 5, 6],
        [4, 5, 6, 7]]) tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
