In [ ]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y,x*y,x/y,x**y

In [5]:
x = torch.arange(4)
x[2],len(x),x.shape

(tensor(2), 4, torch.Size([4]))

In [7]:
A = torch.arange(20).reshape([5,4])
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [8]:
x = torch.arange(4,dtype=torch.float32)
x,sum(x)

(tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
x = torch.arange(40,dtype=torch.float32).reshape(2,5,4)
print(x)
y = x.sum(axis=0)
z = x.sum(axis=[0,1])
print(y,y.shape)
print(z,z.shape)
#指定哪个轴，就是“消灭”哪个轴

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]]) torch.Size([5, 4])
tensor([180., 190., 200., 210.]) torch.Size([4])


In [21]:
x.mean(),x.mean(axis=0)

(tensor(19.5000),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [27]:
A = torch.arange(20,dtype=torch.float32).reshape(5, 4)
print(A)
sum_A = A.sum(axis=1,keepdim=True)
print(A/sum_A)
#这个操作实际上是在做行归一化（Row Normalization）。它计算了每一行中，每个元素占该行总和的比例。这在机器学习中常用于将数据转换为概率分布（例如 Softmax 的前置步骤）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [28]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [29]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [30]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [31]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [33]:
u = torch.tensor([-3.0,4.0])
torch.norm(u),torch.abs(u).sum()
#L2范数        #L1范数

(tensor(5.), tensor(7.))