In [4]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [8]:
x.requires_grad_(True)#等价于 x=torch.arange(4.0,requires_grad=True)
x.grad
#告诉 PyTorch：“这个张量很重要，我要对它求导。”
#准备好接收“导数结果”的容器

In [9]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad == 4 * x

tensor([True, True, True, True])

In [12]:
x.grad.zero_()#梯度清零，否则梯度会累加
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [13]:
x.grad.zero_()
y = x * x
y.sum().backward()#加sum()是为了把向量转为标量
x.grad

tensor([0., 2., 4., 6.])

In [15]:
x.grad.zero_()
y = x * x
u = y.detach()#把u当作了常数系数
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])